# async 关键字

async 关键字用于简化异步操作，是 Promise API 的语法糖。

async 函数的各种写法：

```js
async function fun1() {} // 普通函数

const fun2 = async function () {}; // 函数表达式

const fun3 = async () => {}; // 箭头函数

const obj = { async fun4() {} }; // 对象方法

class MyClass {
    async fun5() {} // 类方法
}
```

<br>

async 修饰的函数为异步函数，异步函数始终返回 Promise 实例。

如果异步函数使用 return 关键字返回了值（如果没有 return 则会返回 undefined），这个值会被 `Promise.resolve()` 包装成一个 Promise 实例。

```js
async function show() {
    return 'ok'; // 返回非 Promise 实例的数据
}
const p1 = show();
console.log('p1', p1); // p1 Promise {<fulfilled>: 'ok'}
```

相当于：

```js
const p2 = new Promise((resolve) => {
    resolve('ok');
});
console.log('p2', p2); // p2 Promise {<fulfilled>: 'ok'}
```

<br>

如果异步函数返回 Promise 实例，则需要异步获取返回值：

```js
async function show() {
    return Promise.resolve('ok');
}
const p1 = show();
console.log('p1', p1); // p1 Promise {<pending>}
setTimeout(console.log, 0, 'p1', p1); // Promise {<fulfilled>: 'ok'}
```

```js
async function show() {
    return Promise.reject('fail');
}
const p1 = show();
console.log('p1', p1); // p1 Promise {<pending>}
setTimeout(console.log, 0, 'p1', p1); // p1 Promise {<rejected>: 'fail'}
```

<br>

如果异步函数内部抛出错误，会返回 rejected 状态的 Promise 实例，值为抛出的错误信息。

```js
async function show() {
    throw '出错了'; // 抛出异常
}
const p1 = show();
console.log('p1', p1); // p1 Promise {<rejected>: '出错了'}
```

相当于：

```js
const p2 = new Promise((_, reject) => {
    reject('出错了');
});
console.log('p2', p2); // p2 Promise {<rejected>: '出错了'}
```

<br><br>

# await 关键字

我们可以在 async 函数的**直接子作用域**中，使用 await 关键字来控制异步操作的执行。

await 关键字用于修饰 Promise 实例，如果修饰的不是 Promise 实例，则会将其转为 Promise 实例。

```js
async function fun() {
    const res = await 1;
    console.log('res', res);
}

console.log('start');
fun();
console.log('end');
```

相当于：

```js
async function fun() {
    await Promise.resolve(1).then((res) => {
        console.log('res', res);
    });
}

console.log('start');
fun();
console.log('end');
```

<br>

await 会等待所修饰的 Promise 实例，直到这个 Promise 实例的状态变成 fulfilled / rejected。此时，如果异步函数没有执行完，await 会将后续代码作为微任务添加到微任务队列中；如果异步函数执行完毕，await 会将 [函数执行完毕] 这个操作作为微任务添加到微任务队列中。

await 关键字前面的代码对应 Promise 执行器中的代码，会同步执行；await 下一行开始的代码对应 then 方法中的代码，属于异步操作。

```js
async function test() {
    console.log('before await');
    const val1 = await new Promise((resolve) => {
        setTimeout(() => {
            resolve('ProResolve');
        }, 1000);
    });
    console.log(val1);
    console.log('after await');
}

console.log('before async');
test();
console.log('after async');
```

上例等效于：

```js
function test() {
    new Promise((resolve) => {
        console.log('before await');
        setTimeout(() => {
            resolve('ProResolve');
        }, 1000);
    }).then((val1) => {
        console.log(val1);
        console.log('after await');
    });
}

console.log('before await');
test();
console.log('after await');
```

<br>

如果 Promise 对象的状态变为 fulfilled，await 关键字会返回该 Promise 对象的值；如果 Promise 对象的状态变为 rejected，则会抛出相应的错误信息。

```js
async function show() {
    const res = await Promise.reject('wrong'); // 这里抛出错误, 后面的语句都不会执行
    console.log('res', res); // 这里不会打印
}
show();
```

可以使用 Promise 实例调用 catch 方法处理错误：

```js
async function show() {
    const res = await Promise.reject('wrong').catch((rea) => rea);
    console.log('res', res); // res wrong
}
show();
```

也可以通过 `try … catch` 语句捕获并处理错误：

```js
async function show() {
    try {
        const res = await Promise.reject('wrong'); // 这里抛出错误, 后面的语句都不会执行
        console.log('res', res); // 这里不会打印
    } catch (error) {
        console.log('error', error); // error wrong
    }
}
show();
```

<br><br>

# await 使用陷阱

1. 对于并行执行的异步任务，其实并不适合用 await 修饰

```js
async function fun() {
    const pro1 = await fetch('url1');
    const pro2 = await fetch('url2');
    // ...
}
```

上例这样写，虽没有错误，但会打破两个 fetch 的并行，这需要等待第 1 个异步任务执行完毕之后，才会执行第 2 个异步任务
所以我们可以不用 await 修饰这些并行执行的异步操作

```js
async function fun() {
    const proA = fetch('url1'); // 只要不加 await，Ajax 就会同时请求
    const proB = fetch('url2');
    const pro1 = await proA;
    const pro2 = await proB;
    console.log(pro1, pro2);
    // ...
}
```

这里更高效的做法：通过 `Promise.all` 组合起来

```js
async function fun() {
    const proA = fetch('url1'); // 只要不加 await，Ajax 就会同时请求
    const proB = fetch('url2');
    const [pro1, pro2] = await Promise.all([proA, proB]);
    // ...
}
```

<br>

2. 如果我们需要在循环中执行异步操作，是不能够直接调用 `forEach` / `map` 这一类方法的。即使我们在回调函数中写了 `await`，`forEach` 也会立刻返回，并不会暂停等到所有异步操作都执行完毕。

```js
async function fun() {
    [1, 2, 3].forEach(async (i) => {
        await someAsyncOperation();
    });
    console.log('done');
}
fun();
```

如果我们希望等待循环中的异步操作都完成之后才继续执行，那我们还是应该使用传统的 `for` 循环

```js
async function fun() {
    for (let i of [1, 2, 3]) {
        await someAsyncOperation();
    }
    console.log('done');
}
fun();
```

更进一步，如果我们想所有操作都并发执行，可以使用 `for await`：
这里的 `for` 循环依然会等到所有的异步操作都完成之后才继续向后执行

```js
async function fun() {
    const pros = [
        someAsyncOperation1,
        someAsyncOperation2,
        someAsyncOperation3,
    ];
    for await (let result of pros) {
        // ...
    }
    console.log('done');
}
fun();
```

<br><br>

# 案例

使用回调函数读取多个文件

```js
const fs = require('fs');

fs.readFile('./demo.html', (err, data1) => {
    if (err) throw err;
    fs.readFile('./demo.html', (err, data2) => {
        if (err) throw err;
        fs.readFile('./demo.html', (err, data3) => {
            if (err) throw err;
            console.log(data1 + data2 + data3);
        });
    });
});
```

使用 async & await 读取多个文件：

```js
const fs = require('fs');
const util = require('util');

// 把 fs.readFile 方法封装成 Promise 实例
const myReadFile = util.promisify(fs.readFile);

async function main() {
    try {
        const data1 = await myReadFile('./demo.html');
        const data2 = await myReadFile('./demo.html');
        const data3 = await myReadFile('./demo.html');
        console.log(data1 + data2 + data3);
    } catch (error) {
        console.log(error);
    }
}

main();
```

<br>

```js
async function foo() {
    console.log(2);
    await null;
    console.log(4);
}
console.log(1);
foo();
console.log(3);
```

1.  打印 `1`
2.  调用异步函数 `foo`
    1.  打印 `2`
    2.  `await` 关键字暂停执行，为立即可用的值 `null` 向消息队列中添加一个任务
3.  退出 `foo`
4.  打印 `3`
5.  同步线程的代码执行完毕
6.  JS 运行时从消息队列中取出任务，恢复 `foo` 的执行
    1.  `await` 取得 `null`
    2.  打印 `4`
7.  `foo` 执行完毕

<br>

如果 `await` 后面是一个期约，则问题会稍微复杂一些。此时，为了执行异步函数，实际上会有两个任务被添加到消息队列并被异步求值。

```js
async function foo() {
    console.log(2);
    console.log(await Promise.resolve(8));
    console.log(9);
}
async function bar() {
    console.log(4);
    console.log(await 6);
    console.log(7);
}
console.log(1);
foo();
console.log(3);
bar();
console.log(5);
```

1.  打印 `1`
2.  调用异步函数 `foo`
    1.  打印 `2`
    2.  `await` 关键字暂停执行，向消息队列中添加一个 Promise 实例在 settle 之后执行的任务
    3.  Promise 实例立即 settle，把给 await 提供值的任务添加到消息队列中
3.  退出 `foo`
4.  打印 `3`
5.  调用异步函数 `bar`
    1.  打印 `4`
    2.  `await` 关键字暂停执行，为立即可用的值 `6` 向消息队列中添加一个任务
6.  退出 `bar`
7.  打印 `5`
8.  同步线程的代码执行完毕
9.  JS 运行时从消息队列中取出任务，恢复 `foo` 的执行
    1.  `await` 取得 `8`
    2.  JS 运行时向消息队列中取出恢复 `foo` 函数的任务
10. JS 运行时从消息队列中取出任务，恢复 `bar` 的执行
    1.  `await` 取得 `6`
    2.  打印 `6`
    3.  打印 `7`
11. `bar` 执行完毕
12. JS 运行时向消息队列中取出恢复 `foo` 函数的任务
    1.  打印 `8`
    2.  打印 `9`
13. `foo` 执行完毕

<br>
